import type { Metadata } from "next";
import "./globals.css";

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: "Stouch Payment",
  description: "Generated by stouch.id",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id" className={`${inter.variable}`} suppressHydrationWarning>
      <head />
      <body className="bg-white text-gray-900 antialiased font-sans dark:bg-gray-950 dark:text-white transition-colors duration-300">
        {children}
      </body>
    </html>
  )
}